app/routes.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Application Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register all of the routes for an application.
    | It's a breeze. Simply tell Laravel the URIs it should respond to
    | and give it the Closure to execute when that URI is requested.
    |
    */

    /**
     * Page Routes
     */

    Route::get('/', array('as' => 'index', 'uses' => 'HomeController@index'));

    Route::get('discover', array('as' => 'discover', 'uses' => 'DiscoverController@index'));

    Route::get('discover/submitSchool', array('uses' => 'DiscoverController@getSubmitSchool'));

    Route::get(
         'dashboard',
             array('as' => 'dashboard', 'uses' => 'HomeController@dashboard', 'before' => 'auth')
    );


    Route::post(
         'college/loadDashboardConfessions',
             array('as' => 'college.dashboardConfessions', 'uses' => 'CollegeController@loadDashboardConfessions')
    );
    Route::post(
         'college/loadMoreComments',
             array('as' => 'college.dashboardConfessions', 'uses' => 'CollegeController@postLoadMoreComments')
    );

    Route::get('college/{slug}', array('as' => 'college', 'uses' => 'CollegeController@index'))
         ->where('slug', '[a-z-]+');

    Route::post(
         'college/{slug}/loadConfessions',
             array('as' => 'college.confessions', 'uses' => 'CollegeController@loadConfessions')
    )
         ->where('slug', '[a-z-]+');


    Route::post(
         'college/lookup',
             array('as' => 'college.lookup', 'uses' => 'CollegeController@lookup')
    );

    Route::get(
         'college/{slug}/getArtworkRequest',
             array('uses' => 'CollegeController@getArtworkRequest')
    )
         ->where('slug', '[a-z-]+');


    Route::get(
         'confession',
             array(
                 'as'   => 'confession',
                 'uses' => 'CollegeController@getConfessionModal'
             )
    );

    Route::get('updates', array('as' => 'updates', 'uses' => 'HomeController@updates'));

    /**
     * Legal Actions
     */

    Route::get(
         'terms',
             array(
                 'as' => 'terms',
                 function () {
                     return View::make('legal.terms');
                 }
             )
    );
    Route::get(
         'privacy',
             array(
                 'as' => 'privacy',
                 function () {
                     return View::make('legal.privacy');
                 }
             )
    );

    /**
     * Handle Any actions that require you be logged in
     * via ajax
     *
     */
    Route::group(
         array('before' => 'auth.ajax'),
             function () {


                 Route::post(
                      'confession',
                          array(
                              'as'   => 'confession.post',
                              'uses' => 'CollegeController@postConfessionModal'
                          )
                 );

                 Route::post(
                      'comment',
                          array(
                              'as'   => 'comment.post',
                              'uses' => 'CollegeController@postConfessionComment'
                          )
                 );

                 Route::post(
                      'college/getArtworkRequest',
                          array('as' => 'submitArtwork.post', 'uses' => 'CollegeController@postArtworkRequest')
                 );

                 Route::post(
                      'college/{slug}/likeConfession',
                          array('as' => 'college.like.confession', 'uses' => 'CollegeController@likeConfession')
                 )
                      ->where('slug', '[a-z-]+');

                 Route::post(
                      'college/{slug}/likeCollege',
                          array('as' => 'college.like', 'uses' => 'CollegeController@likeCollege')
                 )
                      ->where('slug', '[a-z-]+');


                 Route::post(
                      'discover/submitSchool',
                          array('as' => 'submitSchool.post', 'uses' => 'DiscoverController@postSubmitSchool')
                 );
             }
    );

    /**
     * Handle Auth Actions
     */
    Route::group(
         array('prefix' => 'account'),
             function () {
                 Route::get(
                      'activate/{activationkey}',
                          array('as' => 'login.activate', 'uses' => 'AuthController@activateUser')
                 );

                 Route::get(
                      'login',
                          array('as' => 'login.get', 'uses' => 'AuthController@getLogin')
                 );

                 Route::post(
                      'login',
                          array('as' => 'login.post', 'uses' => 'AuthController@postLogin')
                 );

                 Route::get(
                      'login/facebook',
                          array('as' => 'login.facebook', 'uses' => 'AuthController@getLoginFacebook')
                 );

                 Route::get(
                      'login/facebook/callback',
                          array('as' => 'login.facebook.callback', 'uses' => 'AuthController@getLoginFacebookCallback')
                 );

                 Route::get(
                      'logout',
                          array('as' => 'logout', 'uses' => 'AuthController@getLogout')
                 );

                 Route::get(
                      'register',
                          array('as' => 'register.get', 'uses' => 'AuthController@getRegister')
                 );

                 Route::post(
                      'register',
                          array('as' => 'register.post', 'uses' => 'AuthController@postRegister')
                 );

                 Route::get(
                      'login/facebook',
                          array('as' => 'login.facebook', 'uses' => 'AuthController@getLoginFacebook')
                 );

                 Route::get(
                      'login/facebook/callback',
                          array('as' => 'login.facebook.callback', 'uses' => 'AuthController@getLoginFacebookCallback')
                 );

                 Route::get(
                      'password/reset',
                          array('as' => 'passwordReset', 'uses' => 'AuthController@getResetPassword')
                 );

                 Route::get(
                      'forgotPassword',
                          array('as' => 'forgotPassword', 'uses' => 'AuthController@getForgotPassword')
                 );
                 Route::post(
                      'forgotPassword',
                          array('as' => 'forgotPassword.post', 'uses' => 'AuthController@postForgotPassword')
                 );
             }
    );

    /**
     * Handle routes that require authentication to enter
     */

    Route::group(
         array('prefix' => 'account', 'before' => 'auth'),
             function () {

                 Route::get(
                      'preferences',
                          array('as' => 'account.preferences', 'uses' => 'AccountController@getPreferences')
                 );

                 Route::post(
                      'personalInfo',
                          array('as' => 'account.postPersonalInfo', 'uses' => 'AccountController@postPersonalInfo')
                 );

                 Route::post(
                      'accountInfo',
                          array('as' => 'account.postAccountInfo', 'uses' => 'AccountController@postAccountInfo')
                 );

                 Route::post(
                      'changePassword',
                          array('as' => 'account.postChangePassword', 'uses' => 'AccountController@postChangePassword')
                 );

                 Route::post(
                      'closeAccount',
                          array('as' => 'account.postCloseAccount', 'uses' => 'AccountController@postCloseAccount')
                 );
             }
    );

app/models/State.php
<?php

    /**
     * @author Clark Tomlinson  <fallen013@gmail.com>
     * @since 1/29/14, 12:05 PM
     * @link http://www.clarkt.com
     * @copyright Clark Tomlinson © 2014
     *
     */
    class State extends Eloquent
    {

        protected $table = 'states';

        public function colleges()
        {
            return $this->hasMany('College', 'state_code', 'state_code');
        }

        public function getNameAttribute($value)
        {
            return ucwords($value);
        }


    }

app/views/layout/colleges-temp.blade.php
@include('layout.partials.header')

@include('layout.partials.navigation')
@include('layout.partials.navigationUser')
<div class="college-page">

    <div id="home_top" class="full-row large-12 columns"
         style="background-image: @if($college->background_url)url('{{image($college->background_url)}}') @elseurl('{{image('college_default_background_top.jpg')}}')@endif;">

        <span id="home_main_text" class="row large-12 columns">{{$college->name}}</span><br>

        <span id="college_sub_text" class="row large-12">{{$college->city}}, {{Str::upper($college->state_code)}}</span>
        <br><br>

        <div class="stats-container large-6 columns large-centered">
            <div class="college college_stat large-6 columns">
                <span class="confessionCount">
                    {{$college->confessionsCount->count()}}
                </span>
                <span class="college college_stat_name row">
                    Confessions
                </span>
            </div>

            <div class="college college_stat large-6 columns">
                <span class="taccCount">
                    {{$college->likes->count()}}
                </span>
                <span class="college college_stat_name row">
                    Student Taccs
                </span>
            </div>
        </div>


        <div class="submit_cover_art">
            <div class="link">
                Looking to be featured on taccd? <strong>Submit your schools cover art!</strong>
            </div>
        </div>

    </div>
    <div class="row">

        <div class="large-7 columns">
            @yield('content')
        </div>
        <div class="large-5 columns">
            @include('layout.partials.sidebar')
        </div>
    </div>
</div>


@include('layout.partials.footer')

app/views/layout/dashboard.blade.php
@include('layout.partials.header')

@include('layout.partials.navigation')
@include('layout.partials.navigationUser')


<div class="row">

    <div class="large-7 columns">
        @yield('content')
    </div>

    <div class="large-5 columns">
        @include('layout.partials.dashboardsidebar')
    </div>
</div>

@include('layout.partials.footer')

app/views/layout/fullwidth.blade.php
@include('layout.partials.header')

@include('layout.partials.navigation')
@include('layout.partials.navigationUser')

@yield('content')

@include('layout.partials.footer')

app/views/layout/master.blade.php
@include('layout.partials.header')

@include('layout.partials.navigation')
@include('layout.partials.navigationUser')

@yield('content')

@include('layout.partials.footer')

app/views/layout/twocol.blade.php
@include('layout.partials.header')

@include('layout.partials.navigation')
@include('layout.partials.navigationUser')

<div id="home_top">

    <span id="home_main_text">{{$college->name}}</span><br>

    <span id="college_sub_text">{{$college->city}}, {{Str::upper($college->state_code)}}</span> <br><br>


    <table cellpadding="0" cellspacing="0" border="0" style="margin:auto;">

        <tr>

            <td class="college_stat"> {{count($college->confessions)}} <br> <span
                    class="college_stat_name">confessions</span></td>

            <td class="college_stat_splitter"></td>

            <td class="college_stat"> {{count($college->likes)}} <br> <span
                    class="college_stat_name">student taccs</span></td>

    </table>


    <div class="submit_cover_art">
        <div class="link" onClick="javascript:load_form('school_art'); return false;">Looking to be featured on
            taccd? <strong>Submit your schools cover art!</strong></div>
    </div>

</div>
<div class="row">

    <div class="large-7 columns">
        @yield('content')
    </div>
    <div class="large-5 columns">
        @include('layout.partials.sidebar')
    </div>
</div>


@include('layout.partials.footer')