app/routes.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Application Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register all of the routes for an application.
    | It's a breeze. Simply tell Laravel the URIs it should respond to
    | and give it the Closure to execute when that URI is requested.
    |
    */

    /**
     * Page Routes
     */

    Route::get('/', array('as' => 'index', 'uses' => 'HomeController@index'));

    Route::get('discover', array('as' => 'discover', 'uses' => 'DiscoverController@index'));

    Route::get('discover/submitSchool', array('uses' => 'DiscoverController@getSubmitSchool'));

    Route::get(
         'dashboard',
             array('as' => 'dashboard', 'uses' => 'HomeController@dashboard', 'before' => 'auth')
    );


    Route::post(
         'college/loadDashboardConfessions',
             array('as' => 'college.dashboardConfessions', 'uses' => 'CollegeController@loadDashboardConfessions')
    );
    Route::post(
         'college/loadMoreComments',
             array('as' => 'college.dashboardConfessions', 'uses' => 'CollegeController@postLoadMoreComments')
    );

    Route::get('college/{slug}', array('as' => 'college', 'uses' => 'CollegeController@index'))
         ->where('slug', '[a-z-]+');

    Route::post(
         'college/{slug}/loadConfessions',
             array('as' => 'college.confessions', 'uses' => 'CollegeController@loadConfessions')
    )
         ->where('slug', '[a-z-]+');


    Route::post(
         'college/lookup',
             array('as' => 'college.lookup', 'uses' => 'CollegeController@lookup')
    );

    Route::get(
         'college/{slug}/getArtworkRequest',
             array('uses' => 'CollegeController@getArtworkRequest')
    )
         ->where('slug', '[a-z-]+');


    Route::get(
         'confession',
             array(
                 'as'   => 'confession',
                 'uses' => 'CollegeController@getConfessionModal'
             )
    );

    Route::get('updates', array('as' => 'updates', 'uses' => 'HomeController@updates'));

    /**
     * Legal Actions
     */

    Route::get(
         'terms',
             array(
                 'as' => 'terms',
                 function () {
                     return View::make('legal.terms');
                 }
             )
    );
    Route::get(
         'privacy',
             array(
                 'as' => 'privacy',
                 function () {
                     return View::make('legal.privacy');
                 }
             )
    );

    /**
     * Handle Any actions that require you be logged in
     * via ajax
     *
     */
    Route::group(
         array('before' => 'auth.ajax'),
             function () {


                 Route::post(
                      'confession',
                          array(
                              'as'   => 'confession.post',
                              'uses' => 'CollegeController@postConfessionModal'
                          )
                 );

                 Route::post(
                      'comment',
                          array(
                              'as'   => 'comment.post',
                              'uses' => 'CollegeController@postConfessionComment'
                          )
                 );

                 Route::post(
                      'college/getArtworkRequest',
                          array('as' => 'submitArtwork.post', 'uses' => 'CollegeController@postArtworkRequest')
                 );

                 Route::post(
                      'college/{slug}/likeConfession',
                          array('as' => 'college.like.confession', 'uses' => 'CollegeController@likeConfession')
                 )
                      ->where('slug', '[a-z-]+');

                 Route::post(
                      'college/{slug}/likeCollege',
                          array('as' => 'college.like', 'uses' => 'CollegeController@likeCollege')
                 )
                      ->where('slug', '[a-z-]+');


                 Route::post(
                      'discover/submitSchool',
                          array('as' => 'submitSchool.post', 'uses' => 'DiscoverController@postSubmitSchool')
                 );
             }
    );

    /**
     * Handle Auth Actions
     */
    Route::group(
         array('prefix' => 'account'),
             function () {
                 Route::get(
                      'activate/{activationkey}',
                          array('as' => 'login.activate', 'uses' => 'AuthController@activateUser')
                 );

                 Route::get(
                      'login',
                          array('as' => 'login.get', 'uses' => 'AuthController@getLogin')
                 );

                 Route::post(
                      'login',
                          array('as' => 'login.post', 'uses' => 'AuthController@postLogin')
                 );

                 Route::get(
                      'login/facebook',
                          array('as' => 'login.facebook', 'uses' => 'AuthController@getLoginFacebook')
                 );

                 Route::get(
                      'login/facebook/callback',
                          array('as' => 'login.facebook.callback', 'uses' => 'AuthController@getLoginFacebookCallback')
                 );

                 Route::get(
                      'logout',
                          array('as' => 'logout', 'uses' => 'AuthController@getLogout')
                 );

                 Route::get(
                      'register',
                          array('as' => 'register.get', 'uses' => 'AuthController@getRegister')
                 );

                 Route::post(
                      'register',
                          array('as' => 'register.post', 'uses' => 'AuthController@postRegister')
                 );

                 Route::get(
                      'login/facebook',
                          array('as' => 'login.facebook', 'uses' => 'AuthController@getLoginFacebook')
                 );

                 Route::get(
                      'login/facebook/callback',
                          array('as' => 'login.facebook.callback', 'uses' => 'AuthController@getLoginFacebookCallback')
                 );

                 Route::get(
                      'password/reset',
                          array('as' => 'passwordReset', 'uses' => 'AuthController@getResetPassword')
                 );

                 Route::get(
                      'forgotPassword',
                          array('as' => 'forgotPassword', 'uses' => 'AuthController@getForgotPassword')
                 );
                 Route::post(
                      'forgotPassword',
                          array('as' => 'forgotPassword.post', 'uses' => 'AuthController@postForgotPassword')
                 );
             }
    );

    /**
     * Handle routes that require authentication to enter
     */

    Route::group(
         array('prefix' => 'account', 'before' => 'auth'),
             function () {

                 Route::get(
                      'preferences',
                          array('as' => 'account.preferences', 'uses' => 'AccountController@getPreferences')
                 );

                 Route::post(
                      'personalInfo',
                          array('as' => 'account.postPersonalInfo', 'uses' => 'AccountController@postPersonalInfo')
                 );

                 Route::post(
                      'accountInfo',
                          array('as' => 'account.postAccountInfo', 'uses' => 'AccountController@postAccountInfo')
                 );

                 Route::post(
                      'changePassword',
                          array('as' => 'account.postChangePassword', 'uses' => 'AccountController@postChangePassword')
                 );

                 Route::post(
                      'closeAccount',
                          array('as' => 'account.postCloseAccount', 'uses' => 'AccountController@postCloseAccount')
                 );
             }
    );

app/models/College.php
<?php
    use Illuminate\Database\Eloquent\ModelNotFoundException;

    /**
     * @author Clark Tomlinson  <fallen013@gmail.com>
     * @since 1/29/14, 12:05 PM
     * @link http://www.clarkt.com
     * @copyright Clark Tomlinson © 2014
     *
     */
    class College extends Eloquent
    {

        /**
         * @var string
         */
        protected $table = 'colleges';

        /**
         * @return \Illuminate\Database\Eloquent\Relations\HasMany
         */
        public function likes()
        {
            return $this->hasMany('CollegeLikes', 'college_id', 'id');
        }

        /**
         * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
         */
        public function state()
        {
            return $this->belongsTo('State', 'state_code', 'state_code');
        }

        /**
         * @return mixed
         */
        public function confessions()
        {
            return $this->hasMany('Confession', 'college_id', 'id')//                        ->orderBy('id', 'desc')
                        ->orderBy('created_at', 'desc')
                        ->limit(10);
        }

        /**
         * @return \Illuminate\Database\Eloquent\Relations\HasMany
         */
        public function users()
        {
            return $this->hasMany('User', 'college', 'id');
        }

        /**
         * @return \Illuminate\Database\Eloquent\Relations\HasMany
         */
        public function accounts()
        {
            return $this->hasMany('LegacyUser', 'college_id', 'id');
        }

        /**
         * @return mixed
         */
        public function confessionsCount()
        {
            return $this->hasMany('Confession', 'college_id', 'id')
                        ->orderBy('id', 'desc');
        }

        /**
         * @return mixed
         */
        public function topConfessions()
        {
            return $this->hasMany('Confession', 'college_id', 'id')
                        ->orderBy('total_likes', 'desc')
                        ->limit('5');
        }

        /**
         * @return mixed
         */
        public function getTotalStudentsAttribute()
        {
            $users = $this->users()
                          ->count();
            $accounts = $this->accounts()
                             ->count();
            return $users + $accounts;
        }

        /**
         * @return mixed
         */
        public function getTotalConfessionsAttribute()
        {
            return $this->confessionsCount()
                        ->count();
        }

        /**
         * @return mixed
         */
        public function getTotalLikesAttribute()
        {
            return $this->likes()
                        ->count();
        }

        /**
         * @param $limit
         *
         * @return array|static[]
         */
        public static function topColleges($limit)
        {
            return College::join('college_likes', 'college_id', '=', 'id')
                          ->select(DB::raw('*, COUNT(college_id) as total_likes'))
                          ->groupBy('college_id')
                          ->orderBy(DB::raw('total_likes'), 'desc')
                          ->limit($limit)
                          ->get();
        }

        /**
         * @param $slug
         *
         * @return \Illuminate\Database\Eloquent\Model|null|static
         */
        public static function findBySlug($slug)
        {
            return self::where('name', '=', ucwords(Str::slug($slug, ' ')))
                       ->firstOrFail();
        }


    }

app/models/Confession.php
<?php

    /**
     * @author Clark Tomlinson  <fallen013@gmail.com>
     * @since 1/29/14, 12:05 PM
     * @link http://www.clarkt.com
     * @copyright Clark Tomlinson © 2014
     *
     */
    class Confession extends Eloquent
    {

        /**
         * @var string
         */
        protected $table = 'confessions';

        /**
         * @return \Illuminate\Database\Eloquent\Relations\HasMany
         */
        public function likes()
        {
            return $this->hasMany('ConfessionLikes', 'confession_id', 'id');
        }

        /**
         * @return \Illuminate\Database\Eloquent\Relations\HasMany
         */
        public function comments()
        {
            return $this->hasMany('ConfessionComments', 'confession_id', 'id');
        }

        /**
         * @param $limit
         *
         * @return array|static[]
         */
        public static function byLikedColleges($limit)
        {
            $collegeIds = Sentry::getUser()
                                ->collegeLikes()
                                ->get(array('college_id'));

            if (empty($collegeIds->count())) {
                return $collegeIds;
            }

            $collegeIds = array_flatten($collegeIds->toArray());

            return Confession::whereIn('college_id', $collegeIds)
                             ->orderBy('id', 'desc')
                             ->orderBy('created_at', 'desc')
                             ->limit($limit)
                             ->get();
        }

        /**
         * @param $limit
         *
         * @return array|static[]
         */
        public static function topConfessions($limit)
        {
            return Confession::join('confession_likes', 'confession_id', '=', 'id')
                             ->select(DB::raw('*, COUNT(confession_id) as total_likes'))
                             ->groupBy('confession_id')
                             ->orderBy(DB::raw('total_likes'), 'desc')
                             ->limit($limit)
                             ->get();
        }

        /**
         * @return mixed
         */
        public function getTotalCommentsAttribute()
        {
            return $this->comments()
                        ->count();
        }

        /**
         * @param $value
         *
         * @return \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|static
         */
        public function getAccountIDAttribute($value)
        {
            // Todo: Remove if statement after legacy users are converted
            if (User::find($value)) {
                return User::find($value);
            }
            return LegacyUser::find($value);
        }

        /**
         * @param $value
         *
         * @return \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|static
         */
        public function getCollegeIDAttribute($value)
        {
            return College::find($value);
        }
    }

app/models/State.php
<?php

    /**
     * @author Clark Tomlinson  <fallen013@gmail.com>
     * @since 1/29/14, 12:05 PM
     * @link http://www.clarkt.com
     * @copyright Clark Tomlinson © 2014
     *
     */
    class State extends Eloquent
    {

        protected $table = 'states';

        public function colleges()
        {
            return $this->hasMany('College', 'state_code', 'state_code');
        }

        public function getNameAttribute($value)
        {
            return ucwords($value);
        }


    }

app/views/layout/partials/dashboardsidebar.blade.php
<div class="college-page">
    <div class="content_element content_hide_top border_radius_5 row">

        <div class="content_header small-only-text-center medium-only-text-center"> Top Colleges</div>

        <div class="content_text">
            @foreach(College::topColleges(5) as $topCollege)

            <div class="top_confession_element row">
                <div
                    class="large-3 small-4 small-centered  small-only-text-center medium-only-text-center large-uncentered columns">
                    {{ HTML::image('assets/' . $topCollege->avatar_url, false, array('class' => 'border_radius_3
                    top_confession_avatar'))}}
                </div>


                <div
                    class="college_author large-9 small-10 small-centered  small-only-text-center medium-only-text-center large-uncentered columns"
                    style="padding-left: 0">
                    {{HTML::linkRoute('college', $topCollege->name,
                    array(Str::slug($topCollege->name)))}}
                </div>

                <br/>

                <div class="college_confession_other large-12 small-only-text-center medium-only-text-center">
                    <span class="confession_red_text">{{$topCollege->total_students}}</span> students
                    <span class="confession_bullet">•</span>
                    <span class="confession_red_text">{{$topCollege->total_confessions}}</span> confessions

                </div>
            </div>

            @endforeach

        </div>

    </div>

    <br/>

    <div class="content_element border_radius_5 row">

        <div class="content_header small-only-text-center medium-only-text-center"> Top Confessions</div>
        <div class="content_text">
            @foreach(Confession::topConfessions(5) as $topConfession)

            <div class="top_confession_element row">
                <div
                    class="large-3 small-4 small-centered  small-only-text-center medium-only-text-center large-uncentered columns">
                    {{ HTML::image('assets/' . $topConfession->college_id->avatar_url, false, array('class' =>
                    'border_radius_3
                    top_confession_avatar'))}}
                </div>


                <div
                    class="college_author large-9 small-6 small-centered  small-only-text-center medium-only-text-center large-uncentered columns"
                    style="padding-left: 0">
                    {{$topConfession->college_id->name}}
                </div>

                <div
                    class="college_confession large-9 small-12 small-centered  small-only-text-center medium-only-text-center large-uncentered columns"
                    style="padding-left: 0;">
                    {{$topConfession->confession_text}}
                </div>


                <div
                    class="college_confession_other large-7 small-8 columns left push-2  small-only-text-center medium-only-text-center"
                    style="margin-left: 3%">
                    <span class="confession_red_text">{{$topConfession->total_likes}}</span> likes
                    <span class="confession_bullet">•</span>
                    <span class="confession_red_text">{{$topConfession->total_comments}}</span> comments

                </div>
            </div>

            @endforeach

        </div>

    </div>

    <br/>

    <div class="content_element border_radius_5 row">

        <div class="content_header small-only-text-center medium-only-text-center"> Taccd Stats</div>

        <div class="content_text" id="stats">
            <div class="row">
                <div class="large-6 columns">
                    <div class="fa fa-users"></div>
                    <div class="stat_value">{{ $users }}</div>

                    <div class="stat_label">registered users</div>
                </div>
                <div class="large-6 columns">
                    <div class="fa fa-globe"></div>
                    <div class="stat_value">{{ $colleges }}</div>

                    <div class="stat_label">colleges listed</div>
                </div>
            </div>

            <div class="row">
                <div class="large-6 columns">
                    <div class="fa fa-comments-o"></div>
                    <div class="stat_value">{{ $confessions }}</div>

                    <div class="stat_label">posted confessions</div>
                </div>
                <div class="large-6 columns">
                    <div class="fa fa-heart"></div>
                    <div class="stat_value">{{ $likes }}</div>

                    <div class="stat_label">taccd confessions</div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/layout/partials/footer.blade.php
<div class="footer_wrap full-row">
    <div class="footer-container row">
        <div class="footer large-10 columns">
            <span class="">&copy; 2013-{{ date('Y')}} <strong>Taccd.</strong></span>
            {{HTML::linkRoute('index', 'Home')}}
            <a href="#" class="search_request_form_link">School Request</a>
            <a href="javascript:void();">Advertise</a>
            <a href="#contact">Contact</a>
            {{HTML::linkRoute('terms', 'Terms')}}
            {{HTML::linkRoute('privacy', 'Privacy')}}
        </div>
    </div>
</div>
@include('layout.partials.modal')

<script type="text/javascript">
    Core.init();

    if (typeof Pages.<?php echo Route::currentRouteName(); ?> === 'function') {
        Pages.<?php echo Route::currentRouteName(); ?>();
    }
</script>
</body>
</html>

app/views/layout/partials/header.blade.php
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Taccd - @yield('title')</title>

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--    Stylescripts-->
    {{ stylesheet_link_tag() }}


<!--    Scripts-->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-44189110-1', 'taccd.com');
        ga('send', 'pageview');

    </script>
    {{ javascript_include_tag() }}

    <script type="text/javascript">
        var baseUrl = '{{URL::route('index')}}/';
        var controllerUrl = '{{URL::current()}}/';
    </script>
    <link href="//fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{{image('favicon.png')}}" type="image/x-icon"/>

    <meta name="description" content="The first social platform to share, discover, and discuss real college confessions from schools across the United States."/>

</head>
<body>

app/views/layout/partials/modal.blade.php
<div class="reveal-modal" data-reveal>
    <h2></h2>
    <div data-alert class="alert-box hide radius"></div>

    <div class="content">
    </div>
    <a class="close-reveal-modal">&#215;</a>
</div>

app/views/layout/partials/navigation.blade.php
<div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name">
                <a href="{{URL::route('index')}}">
                    {{HTML::image('assets/taccd_logo.png')}}
                </a>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
        </ul>

        <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
                @if(!Sentry::check())
                <li><a href="#" class="register">Join</a></li>
                <li><a href="#" class="login">Log In</a></li>
                <li class="social"><a href="https://twitter.com/taccd"><i class="fa fa-twitter"></i></a></li>
                <li class="social"><a href="https://www.facebook.com/taccd"><i class="fa fa-facebook"></i></a></li>
                @endif

            </ul>

            <!-- Left Nav Section -->
            <ul class="left">
                <li>
                    <a href="{{URL::route('index')}}">
                        {{HTML::image('assets/home.png')}}
                        <span class="hide-for-medium-up">Home</span>
                    </a>
                </li>
                <li>
                    <a href="{{URL::route('discover')}}">
                        {{HTML::image('assets/discover.png')}}
                        <span class="hide-for-medium-up">Discover</span>
                    </a>
                </li>
                <li>
                    <a href="{{URL::route('index')}}">
                        {{HTML::image('assets/community.png')}}
                        <span class="hide-for-medium-up">Community</span>
                    </a>
                </li>
            </ul>
        </section>
    </nav>
</div>

app/views/layout/partials/sidebar.blade.php
@if(Sentry::check())
<div class="content_element row"
     style="margin-bottom: 15px; margin-top: 15px; margin-left: -11px; background-color: transparent; border: 0">
    <a class="submit other_submit border_radius_5 @if(User::likesCollege($college->id)) taccd @endif" id="taccd_school"
       data-id="{{$college->id}}">
        @if(User::likesCollege($college->id)) Remove Tacc @else Tacc School @endif
    </a>

    <div class="large-6 columns right">
        <div id="fb-root"></div>
        <script>(function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div class="fb-share-button" data-href="{{URL::current()}}" data-type="button_count"></div>
        &nbsp;&nbsp;
        <span style="position: relative; top: 4px;"><a href="https://twitter.com/share" class="twitter-share-button"
                                                       data-lang="en" data-count="none">Tweet</a>
            <script>!function (d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (!d.getElementById(id)) {
                        js = d.createElement(s);
                        js.id = id;
                        js.src = "https://platform.twitter.com/widgets.js";
                        fjs.parentNode.insertBefore(js, fjs);
                    }
                }(document, "script", "twitter-wjs");</script>
        </span>
    </div>
</div>
@endif

<div class="content_element border_radius_5 content_hide_top row large-12 columns">

    <div class="content_header"> Top {{$college->abbreviation}} Confessions</div>

    <div class="content_text">

        @foreach($college->topConfessions as $topConfession)
        <div class="top_confession_element row">
            <span class="large-3 columns">

                @if($topConfession->anonymous)
                {{HTML::image('assets/' . $topConfession->college_id->avatar_url, false, array('class' => 'border_radius_3 top_confession_avatar')) }}
                 @else
            {{ HTML::image($topConfession->account_id->avatar(), false, array('class' => 'border_radius_3
                top_confession_avatar'))}}@endif

            </span>


            <span class="college_author"> {{$college->name}}</span>

            <div class="college_confession top_confession_limits large-9 columns">
                {{$topConfession->confession_text}}
            </div>

            <div class="college_confession_other large-12 columns push-3" style="clear:both;">

                <span id="top_confession_{{$topConfession->id}}">{{$topConfession->created_at->diffForHumans()}}</span>
                <span class="confession_bullet">&bull;</span>
                <span class="confession_red_text">{{$topConfession->likes->count()}} {{Str::plural('tacc', $topConfession->likes->count())}} </span>
                <span class="confession_bullet">&bull;</span>

                <span class="confession_red_text">{{$topConfession->comments->count()}}
                    {{Str::plural('comment', $topConfession->comments->count())}}
                </span>
            </div>
        </div>

        @endforeach

    </div>

</div>